### ISSUE TITLE
To add HLV support to Differ

### ISSUE THREAD

**Issue by darshan-na** [couchbase/xdcrDiffer#97]
Prerequisite : To make some of the utility functions that are essential for parsing HLV public, so that differ can use them to construct HLV for example `parseHlvFields(cas uint64, xattr []byte) (cvCas uint64, src hlv.DocumentSourceId, cvVer uint64, pvMap, mvMap hlv.VersionsMap, err error)`

To update the version of goxdcr and gomemcahced to support HLV

**Comment by sumukhbhat2701** [comment]
@darshan-na shouldn't this be closed as part of one of the PRs?
